#!/usr/bin/env python3

# Color lines from stdin alternatingly and print them to stdout.
#
# 2014  Bence Kalmar

import os
import re
import sys

import termcolor

nr = 1
for l in sys.stdin:
    highlight = None if nr % 2 else "on_white"
    termcolor.cprint(l.rstrip("\n"), None, highlight)
    nr += 1
