#!/bin/bash

# Output a complete HTML5 page using `markdown_py` and the arguments given.
#
# 2015  Bence Kalmar

cat <<EOF
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8">
</head>

<body>

EOF

markdown_py --output_format=html5 "${@}"

cat <<EOF

</body>
</html>
EOF
